### PR TITLE
Kotlin code

### PR DESCRIPTION
**Pull request by ngangavic**
Covid-19-Tracker kotlin code and some few additions to the alert dialogs.

### CODE REVIEW

**Comment by ngangavic** [comment]
I used the same xml layouts.

**Comment by joelkanyi** [comment]
Would it still have the java files or it will be now a Kotlin application

**Comment by joelkanyi** [comment]
Am still learning Kotlin so if we convert the entire application to Kotlin, I'll just be floating "sitaelewa itu"

**Comment by ngangavic** [comment]
I haven't touched the java code. I created a package for kotlin so don't have any worries for the java code its still there. The only changes I made is the manifest where I set the app to start from the kotlin code.

**Comment by joelkanyi** [comment]
So the repository would still have the application files in java plus the added kotlin ama?

**Comment by ngangavic** [comment]
Yes.You can check out the structure in my repo.

**Comment by joelkanyi** [comment]
Let me check if there'll be no effect I'll merge it

**Comment by joelkanyi** [comment]
Thanks bro, nmeicheki code structure  yako na iko fine it is not conflicting with my code, I'll merge the changes

**Comment by joelkanyi** [comment]
👍

**Pull request merged**
