### PR TITLE
app icon

### PR DESCRIPTION
**Pull request by ngangavic**
App icon for all devices. Some devices could not display the icon as hdpi.

### CODE REVIEW

**Comment by joelkanyi** [comment]
So which icon are we using now

**Review by joelkanyi — COMMENTED** [review]
What about that icon for CoronaVirus

**Comment by ngangavic** [comment]
I used the same icon but generated it for all screen densities.

**Comment by joelkanyi** [comment]
Okay

**Comment by joelkanyi** [comment]
@ngangavic hey bro I had some suggestions concerning the app
First I want that we add the global statistics.
Then we include cases, and deaths per day
Flags for each country 
Then am working on find an API that is real time, azin when cases are reported, it updates s our app
Also some one asked me to use retrofit other that volley 
Also we include a tab for some news about CoronaVirus
A tab for signs and symptoms 

How do you see about that?

**Comment by joelkanyi** [comment]
Then someone asked me about caching data so as to minimize loading time

Then give me you whatsapp number so that we could be sharing more

Mine : 0706003891

**Comment by ngangavic** [comment]
It's a good idea. But hapo kwa retrofit I defer 😁. I don't like retrofit simply because if I require to load images I will add another library to do so making the end apk lager. For volley it has everything including the image loader.

**Comment by joelkanyi** [comment]
Thats fine, let's use volley basi

**Comment by ngangavic** [comment]
> Then someone asked me about caching data so as to minimize loading time
> 
> Then give me you whatsapp number so that we could be sharing more
> 
> Mine : 0706003891

0700352822

**Comment by joelkanyi** [comment]
Then kuna ingine ya mwisho but sijui kama tutamake, azin hapo juu ya mahali inaleta Statistics za kila country, I was suggesting if we could try and show first the global statistics, then country yenye user ako then msee akiclick, inaleta counties, but iyo feature ikue ya Kenya

**Comment by ngangavic** [comment]
It can be done as long as the data is available for each county. Lack of data can be the only challenge

**Pull request merged**
